### ISSUE TITLE
Media Tree - Many Users

### ISSUE THREAD

**Issue by goobber** [samluescher/django-media-tree#35]
Hi, I'm new using Django.

I am searching for a solution to manage files: allow multiple users to upload, save files to a folder(s), download files, delete files and search files. The users won't have access to the Admin page. It would be nice but not required for now to have a restriction on which users can delete or download files or certain files...

Can Media Tree be used? If not, would you know of a solution and point me in the right direction?

Thank you very much!!!

**Comment by samluescher** [comment]
Media Tree would be an option for your backend, managing your, well, tree of files. You'd have to create a custom frontend though, as this app is mainly intended to be used interactively from the admin.

**Comment by bittner** [comment]
With [django CMS](http://django-cms.readthedocs.org/en/develop/user/tutorial/create_page_content.html) and the cmsplugins provided by Media Tree managing media files from the front-end should work, shouldn't it?

Django CMS plugins are intended to provide front-end editing capabilities on a Django website.

**Comment by samluescher** [comment]
I think he needs something with a public interface, for site users to upload and delete files. Either way would require a custom app that is exposed publicly.
