### ISSUE TITLE
Django 1.8 support? (aka "form MediaTreeImagePluginForm needs updating")

### ISSUE THREAD

**Issue by bittner** [samluescher/django-media-tree#37]
I'm trying to get `django-media-tree` working with Django 1.8.3 and django CMS 3.1.2 (with Python 2.7.5), and I'm getting the following errors for all cms-plugins:
``` python
  ...
  File "<...>/site-packages/media_tree/contrib/cms_plugins/media_tree_image/cms_plugins.py", line 14, in <module>
    class MediaTreeImagePluginForm(MediaTreePluginFormBase):
  File "<...>/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form MediaTreeImagePluginForm needs updating.
```
This analogously affects all cms-plugins,

* MediaTreeImagePluginForm
* MediaTreeSlideshowPluginForm
* MediaTreeGalleryPluginForm
* MediaTreeListingPluginForm

## Fixing the issue for Django 1.8 

The reasons and the fix are described on [StackOverflow](http://stackoverflow.com/questions/26103005/django-core-exceptions-improperlyconfigured). It's a backwards-incompatible change from Django 1.7 to 1.8.

I see there there hasn't been a lot of activity on this project this year. Hence, most probably Django 1.8 compatibility has not been tackled yet. I'm going to prepare a pull request.

**Comment by samluescher** [comment]
Re/ 1.8 and project activity, @bittner you may want to check out this branch, where heavy development has been happening lately:
https://github.com/samluescher/django-media-tree/tree/feature/treebeard

This will be merged into master shorty and replace `mptt` with `treebeard`, amongst many drive-by fixes (and Django-native migrations.) 

Regarding the CMS plugins, the plan is to move those out of the django-media-tree repo and into their own project, but this shouldn't affect your projects nor require migration once it happens (simply an additional entry in INSTALLED_APPS.)
